### ISSUE TITLE
compiler troubles

### ISSUE THREAD

**Issue by noiseexplosion** [chovelyoukai/trenchbroom-source-tools#1]
could you be more specific about the way the directory is meant to be set up? i think i figured it out? but I'm still running into an issue, here's the compiler output:
#### Error 'FailedToStart' occurred when communicating with process

test output:
#### Exporting map file 'C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mapsrc\unnamed-compile.map'

let me know if you can be of any help. i'd also appreciate some clarification on the way the fgd files are supposed to work. i'm not able to map the mdl files to the entities

**Comment by chovelyoukai** [comment]
Hi, I think the main issue is how you are running MapToVmf. Since it's a Java program, it has to be run like this:

`java -jar /path/to/MapToVmf.jar <options here>`

Secondly, it looks like you're trying to compile maps for Half-Life. If that is the case, these scripts won't work because Half-Life is a GoldSrc game and doesn't have Source engine tools like vbsp/vvis/vrad, and the GoldSrc tools don't support VMF files anyway (you can just use plain .map files). However, if you are trying to port Half-Life .map files to a Source engine game, you should be able to use MapToVmf to help with that.

Finally, based on your paths, it looks like you're running on Windows. Just in case you weren't aware, the scripts are meant to run on Linux, and on Windows you can run Source engine tools like vbsp directly. It may be possible for the scripts to work on Windows if you have WSL or Cygwin, or some other POSIX environment installed, but I'm not sure.

**Comment by chovelyoukai** [comment]
Regarding the FGD, I don't know if TrenchBroom can render Half-Life models, and it probably will never be able to render Source engine models. They use the same .mdl suffix as Quake, but the formats are actually different.
